#!/bin/bash

# Remove programs excluded from the UltraScan3 macOS package before installation
# so that upgrading over a previous install does not leave stale excluded binaries.
#
# Keep this list in sync with @excluded_progs in macOS-x64/utils/fixdependencies.pl

PRODUCT_HOME="/Applications/__PRODUCT__"

for prog in \
    us_comproject \
    us_comproject_academic \
    us_protocoldev \
    us_reporter_gmp \
    us_audit_trail_gmp \
    us_esigner_gmp \
; do
    rm -rf "${PRODUCT_HOME}/bin/${prog}.app" "${PRODUCT_HOME}/bin/${prog}"
done

exit 0
